version: '3'
services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata/data:/var/lib/postgresql/data
    env_file:
      - env

  web:
    restart: always

    build: ./web/
    ports:
    - "8000:8000"
    expose:
    - "8000"
    env_file: env
    depends_on:
      - postgres
      - nginx
    links:
      - postgres

  nginx:
    restart: always
    build: ./nginx/
    ports:
    - "80:80"
    volumes:
    - ./web:/data/web


  bot:
    restart: always
    ports:
    - "8443:8443"
    working_dir: /data/bot/
    build: ./bot/
    env_file: ./bot/env
